#ifndef CP_MODULES_DATA_STRUCTURES_HPP
#define CP_MODULES_DATA_STRUCTURES_HPP

/**
 * @file Data_Structures.hpp
 * @brief Umbrella include for advanced data structures.
 */

#include "algebra/Algebra.hpp"
#include "data_structures/bit/BinaryTrie.hpp"
#include "data_structures/bit/DynamicBitset.hpp"
#include "data_structures/bit/FastSet.hpp"
#include "data_structures/bit/WaveletMatrix.hpp"
#include "data_structures/fenwick/DualFenwickTree.hpp"
#include "data_structures/fenwick/FenwickTree.hpp"
#include "data_structures/fenwick/FenwickTree2D.hpp"
#include "data_structures/fenwick/FenwickTree2D_Dense.hpp"
#include "data_structures/fenwick/GroupFenwickTree.hpp"
#include "data_structures/fenwick/GroupFenwickTree2D.hpp"
#include "data_structures/fenwick/GroupFenwickTree2D_Dense.hpp"
#include "data_structures/fenwick/RangeAddFenwickTree.hpp"
#include "data_structures/line/ConvexHullTrick.hpp"
#include "data_structures/line/LiChaoTree.hpp"
#include "data_structures/line/RangeLineHull.hpp"
#include "data_structures/offline/OfflineDynamicQueries.hpp"
#include "data_structures/offline/ParallelBinarySearch.hpp"
#include "data_structures/offline/PointAddRectangleSum.hpp"
#include "data_structures/offline/RectangleAddPointSum.hpp"
#include "data_structures/offline/RectangleAddRectangleSum.hpp"
#include "data_structures/range_query/Mo.hpp"
#include "data_structures/range_query/DisjointSparseTable.hpp"
#include "data_structures/range_query/MonoidSparseTable.hpp"
#include "data_structures/range_query/SparseDeltaSweep.hpp"
#include "data_structures/range_query/SparseTable.hpp"
#include "data_structures/range_query/SqrtDecomposition.hpp"
#include "data_structures/segment_tree/ActedLazySegTree.hpp"
#include "data_structures/segment_tree/DualSegmentTree.hpp"
#include "data_structures/segment_tree/DynamicLazySegTree.hpp"
#include "data_structures/segment_tree/DynamicSegmentTree.hpp"
#include "data_structures/segment_tree/LazySegTree.hpp"
#include "data_structures/segment_tree/MonoidSegmentTree.hpp"
#include "data_structures/segment_tree/PersistentSegTree.hpp"
#include "data_structures/segment_tree/PrefixFlipTree.hpp"
#include "data_structures/segment_tree/RollbackLazySegTree.hpp"
#include "data_structures/segment_tree/SegTreeBeats.hpp"
#include "data_structures/segment_tree/SegmentTree.hpp"
#include "data_structures/segment_tree/SegmentTreeHull.hpp"
#include "data_structures/segment_tree/SegmentTreeMinAddSearch.hpp"
#include "data_structures/sequence/KSmallestSum.hpp"
#include "data_structures/sequence/SlidingWindowAggregation.hpp"
#include "data_structures/sequence/Treap.hpp"
#include "data_structures/tree/LinkCutTree.hpp"
#include "data_structures/tree/MeldableHeap.hpp"
#include "data_structures/union_find/DSURollback.hpp"
#include "data_structures/union_find/PotentializedUnionFind.hpp"
#include "data_structures/utility/CSR.hpp"
#include "data_structures/utility/Cumsum2D.hpp"
#include "data_structures/utility/Doubling.hpp"
#include "data_structures/utility/IndexCompression.hpp"
#include "data_structures/utility/Intervals.hpp"
#include "data_structures/utility/RemovableQueue.hpp"
#include "data_structures/utility/StaticRangeFrequency.hpp"

#endif
